

CREATE TABLE IF NOT EXISTS `TWITTER_USER` (
    ID BIGINT(255),
	NAME VARCHAR(500),
	SCREEN_NAME VARCHAR(500),
	PROFILE_IMAGE_URL TEXT,
	PROFILE_IMAGE_URL_HTTPS TEXT,
    URL TEXT,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS `IMAGE` (
    ID INTEGER AUTO_INCREMENT,
    USER_ID BIGINT(255),
	IMAGE_URL TEXT,
	IMAGE_LOCATION TEXT,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS `TWEET` (
    ID INTEGER AUTO_INCREMENT,
	TEXT VARCHAR(500),
	TWEET_ID BIGINT(255),
	LANG VARCHAR(255),
	IMAGE_URL TEXT,
	IMAGE_LOCATION TEXT,
	SCREEN_NAME VARCHAR(500),
	RETWEET_COUNT INTEGER,
	FAVORITE_COUNT INTEGER,
	PRIMARY KEY (id)
);