CREATE TABLE IF NOT EXISTS `TWITTER_USER` (
    ID BIGINT(255),
	NAME VARCHAR(500),
	SCREEN_NAME VARCHAR(500),
	PROFILE_IMAGE_URL TEXT,
	PROFILE_IMAGE_URL_HTTPS TEXT,
    URL TEXT,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS `USER_PROFILE_IMAGE` (
    ID BIGINT(255),
	IMAGE_URL TEXT,
	IMAGE_LOCATION TEXT,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS `TWEET_IMAGE` (
    TWEET_ID BIGINT(10),
	IMAGE_URL VARCHAR(500),
	IMAGE_LOCATION TEXT,
    PRIMARY KEY (TWEET_ID, IMAGE_URL)
);

CREATE TABLE IF NOT EXISTS `TWITTER_CHANNEL` (
	SCREEN_NAME VARCHAR(500),
    FOLLOWER_COUNT BIGINT(255),
    PRIMARY KEY (SCREEN_NAME)
);

CREATE TABLE IF NOT EXISTS `TWEET_SEARCH_PARAMETER` (
	QUERY VARCHAR(500),
    SINCE_ID BIGINT(255),
    RESULT_TYPE VARCHAR(100),
    INCLUDE_ENTITIES DATETIME,
    UNTIL BOOLEAN,
    PRIMARY KEY (QUERY)
);

CREATE TABLE IF NOT EXISTS `TWEET` (
	ID BIGINT(255),
	TEXT TEXT,
	LINK TEXT,
	LANG VARCHAR(255),
	RETWEET_COUNT INTEGER,
	FAVORITE_COUNT INTEGER,
	RETWEETED BOOLEAN,
	FAVORITED BOOLEAN,
	TWITTER_USER_ID BIGINT(255),
	TWITTER_USER_NAME TEXT,
	CREATED_AT DATETIME,
	ORIGINAL_TWITTER_NAME TEXT,
	ORIGINAL_LINK TEXT,
	ORIGINAL_CREATED_AT DATETIME,
	ORIGINAL_TEXT TEXT,
	PRIMARY KEY (ID)
);