

CREATE TABLE IF NOT EXISTS `TWITTER_USER` (
    ID BIGINT(255),
	NAME VARCHAR(500),
	SCREEN_NAME VARCHAR(500),
	PROFILE_IMAGE_URL TEXT,
	PROFILE_IMAGE_URL_HTTPS TEXT,
    URL TEXT,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS `USER_PROFILE_IMAGE` (
    ID BIGINT(255),
	IMAGE_URL TEXT,
	IMAGE_LOCATION TEXT,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS `TWEET_IMAGE` (
    TWEET_ID BIGINT(10),
	IMAGE_URL VARCHAR(500),
	IMAGE_LOCATION TEXT,
    PRIMARY KEY (TWEET_ID, IMAGE_URL)
);

CREATE TABLE IF NOT EXISTS `TWEET` (
	ID BIGINT(255),
	TEXT TEXT,
	link text,
	LANG VARCHAR(255),
	RETWEET_COUNT INTEGER,
	FAVORITE_COUNT INTEGER,
	retweeted boolean,
	favorited boolean,
	twitter_user_id BIGINT(255),
	twitter_user_name TEXT,
	created_at datetime,
	original_twitter_name text,
	original_link text,
	original_created_at datetime,
	original_text text,
	PRIMARY KEY (id)
);